// <auto-generated />
namespace Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mapeo_Precio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mapeo_Precio));
        
        string IMigrationMetadata.Id
        {
            get { return "202005072203400_Mapeo_Precio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
